In [1]:
import numpy as np
import qinfer as qi
import qutip as qu
import matplotlib.pyplot as plt
from custom_models import simple_precession_with_noise
from optimization import *

In [13]:
model = simple_precession_with_noise()
prior = qi.UniformDistribution([[0, 1], [0, 1]])
updater = qi.SMCUpdater(model, 500, prior)


true_omegas = np.array(np.array([[0, 0.33]]))
est_omegas = []

In [15]:
cov = updater.est_covariance_mtx()

In [17]:
np.linalg.norm(cov)

0.11823978494460799

In [18]:
updater.particle_covariance_mtx()

TypeError: ParticleDistribution.particle_covariance_mtx() missing 2 required positional arguments: 'weights' and 'locations'

In [28]:
guess = generate_guesses()
guess.dtype = model.expparams_dtype
print(model.expparams_dtype)
guess.dtype
# print(guess)

[('t', 'float', 1)]


/tmp/ipykernel_96050/3858443391.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  guess.dtype = model.expparams_dtype


dtype([('t', '<f8')])

In [39]:
w_0, w_1 = updater.hypothetical_update(np.array([0, 1]), guess)

In [40]:
w_0.shape

(1, 500)

In [41]:
w_1.shape

(1, 500)

In [43]:
w_0.dtype

dtype('float64')

In [48]:
w_0[0, :]

array([2.70051459e-03, 9.29057275e-04, 1.82801614e-03, 1.18164743e-03,
       2.05476951e-03, 1.43027310e-04, 2.79465798e-03, 1.83569095e-03,
       1.11037293e-03, 2.45850227e-03, 2.08740449e-03, 3.56192309e-03,
       3.61039389e-03, 1.20968242e-03, 1.53218434e-03, 1.20110690e-03,
       2.56235802e-03, 2.41281219e-03, 1.09453298e-03, 3.49399841e-03,
       1.26043331e-03, 2.73843266e-03, 4.78750573e-04, 4.36816856e-04,
       2.59535418e-03, 6.97407739e-04, 2.53211389e-03, 2.19023132e-03,
       3.66049398e-03, 7.61998462e-04, 3.19881148e-03, 1.06622345e-03,
       2.49850305e-03, 2.85508233e-03, 4.23654807e-04, 6.70170949e-04,
       2.03555743e-03, 3.59111994e-03, 8.37296270e-04, 1.65753805e-03,
       2.21439247e-03, 3.05179936e-03, 1.97754959e-03, 1.98526759e-03,
       1.52973514e-03, 2.31925238e-03, 2.47457345e-03, 1.70414834e-03,
       1.64920018e-04, 3.47085349e-03, 1.27425367e-03, 2.01553908e-03,
       2.03679892e-03, 3.56501508e-03, 2.54374160e-03, 1.91698082e-03,
      

In [59]:
print(updater.particle_covariance_mtx(w_0[0, :], updater.particle_locations))

print(updater.particle_covariance_mtx(w_1[0, :], updater.particle_locations))


new_weights = [w_0, w_1]
np.linalg.norm(np.sum(np.array([updater.particle_covariance_mtx(w_i[0, :], updater.particle_locations) for w_i in new_weights ]), axis=1)/guess['t'])


[[ 0.10481178 -0.00813994]
 [-0.00813994  0.0828724 ]]
[[0.05376274 0.00177068]
 [0.00177068 0.08537865]]


0.25935199380076873

In [63]:
guess.copy()

array([(0.61703487,)], dtype=[('t', '<f8')])

In [62]:
updater.model.modelparam_names

['\\omega', 'J']

In [61]:
guess[updater.model.expparams_dtype]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [44]:
updater.particle_locations

array([[9.16741571e-01, 5.37555053e-01],
       [4.66704079e-01, 6.91246571e-01],
       [6.07535757e-01, 1.49760162e-01],
       [5.45661676e-01, 4.64904721e-01],
       [1.55280712e-01, 9.33759609e-01],
       [3.54166310e-01, 2.88985299e-02],
       [9.41015967e-01, 6.37327823e-02],
       [6.08118438e-01, 2.88187550e-01],
       [4.72586836e-01, 7.99691790e-01],
       [6.57692111e-01, 2.80288033e-01],
       [6.64171207e-01, 9.46995615e-01],
       [7.97472234e-01, 2.03546999e-01],
       [8.40800741e-01, 1.58029588e-02],
       [5.62506773e-01, 1.01314059e-01],
       [2.38949180e-01, 6.57730878e-01],
       [5.55402126e-01, 3.34178981e-01],
       [8.36349650e-01, 8.52583382e-01],
       [1.53622357e-01, 3.52749404e-01],
       [5.53803206e-01, 8.93283260e-02],
       [3.29659221e-02, 2.26130256e-01],
       [5.27730763e-01, 7.10941880e-01],
       [9.44287321e-01, 1.37267435e-01],
       [3.31027233e-01, 3.21927846e-01],
       [4.81811309e-01, 2.61621938e-01],
       [7.294936

In [64]:
def square(numbers):
    for n in numbers:
        yield n ** 2

In [65]:
gen = square([1, 2, 3])

In [66]:
list(gen)

[1, 4, 9]

In [69]:
list(square([1, 2, 3]))

[1, 4, 9]

In [93]:
prior.sample()

array([[0.64827637, 0.15674025]])

In [90]:
rng = np.random.default_rng(seed=1)
n_cases = 2
true_values_list = [np.array([0, rng.uniform(size=1)[0]]) for _ in range(n_cases)]

In [92]:
true_values_list

[array([0.        , 0.51182162]), array([0.       , 0.9504637])]

In [106]:
all_data = [[updater.est_covariance_mtx(), updater.est_covariance_mtx()], [updater.est_covariance_mtx(), updater.est_covariance_mtx()], [1, 2, 3]]
print(all_data)

[[array([[ 0.08295241, -0.0039341 ],
       [-0.0039341 ,  0.08407491]]), array([[ 0.08295241, -0.0039341 ],
       [-0.0039341 ,  0.08407491]])], [array([[ 0.08295241, -0.0039341 ],
       [-0.0039341 ,  0.08407491]]), array([[ 0.08295241, -0.0039341 ],
       [-0.0039341 ,  0.08407491]])], [1, 2, 3]]


In [109]:
[np.mean(i, axis=0) for i in all_data]

[array([[ 0.08295241, -0.0039341 ],
        [-0.0039341 ,  0.08407491]]),
 array([[ 0.08295241, -0.0039341 ],
        [-0.0039341 ,  0.08407491]]),
 2.0]

In [110]:
a = None
if not a:
    print("hola")

hola


In [102]:
np.mean([updater.est_covariance_mtx(), updater.est_covariance_mtx()], axis=0)

array([[ 0.08295241, -0.0039341 ],
       [-0.0039341 ,  0.08407491]])

In [ ]:

from generate_experiments import run_case

rng = np.random.default_rng(seed=1)

number_of_cases = 3
number_of_shots = 3

true_values_list = [np.array([0, rng.uniform(size=1)[0]]) for _ in range(number_of_cases)]

[run_case(true_values_i, number_of_shots) for true_values_i in true_values_list]

In [112]:
import h5py

In [118]:
hf = h5py.File("prueba.hdf5", "w")


In [119]:
hf['/case_1/data'] = true_values_list


In [120]:
hf['/case_1/data'].attrs['number_of_shots'] = 3

In [189]:
with h5py.File("prueba.hdf5", "a") as data_file:
    # data_file['/case_1/data'] = true_values_list
    # data_file['/case_1/data'].attrs['number_of_shots'] = 3
    last_key = list(data_file.keys())[-1]
    


In [204]:
case_no = int(last_key.lstrip("case_"))
new_case_no = case_no + 1
new_case = "case_" + str(new_case_no)
data_file[new_case]

In [205]:
new_case

'case_2'

In [178]:
# hf_in = h5py.File('prueba.hdf5', 'w')
hf_in.close()

In [174]:
"case_1"

'case_1'

In [176]:
last_case = list(hf_in.keys())[-1]

hf_in[str(last_case)]



TypeError: Not a location id (invalid object ID)

In [136]:
list(hf_in.keys())

case_1 = hf_in['case_1/data']

In [144]:
hf_in['case_1/data'][()]

array([[0.        , 0.51182162],
       [0.        , 0.9504637 ]])

In [146]:
aux_dict  = {"a" : [updater.est_covariance_mtx(), updater.est_covariance_mtx()],
     "b" : [updater.est_covariance_mtx(), updater.est_covariance_mtx()],
     "c" : [1, 2, 3]}

In [149]:
np.mean(aux_dict["a"], axis=0)

array([[ 0.08295241, -0.0039341 ],
       [-0.0039341 ,  0.08407491]])

In [151]:
aux_dict2 = aux_dict.copy()

In [152]:
aux_dict2["a"] = np.mean(aux_dict2["a"], axis=0)