In [1]:
import numpy as np
import qinfer as qi
import qutip as qu
import matplotlib.pyplot as plt
from custom_models import simple_precession_with_noise
from optimization import *

In [2]:
model = simple_precession_with_noise()
prior = qi.UniformDistribution([[0, 1], [0, 1]])
updater = qi.SMCUpdater(model, 500, prior)


true_omegas = np.array(np.array([[0, 0.33]]))
est_omegas = []

In [3]:
cov = updater.est_covariance_mtx()

In [4]:
np.linalg.norm(cov)

0.1160951474935355

In [5]:
updater.particle_covariance_mtx()

TypeError: ParticleDistribution.particle_covariance_mtx() missing 2 required positional arguments: 'weights' and 'locations'

In [ ]:
guess = generate_guesses()
guess.dtype = model.expparams_dtype
print(model.expparams_dtype)
guess.dtype
# print(guess)

[('t', 'float', 1)]


/tmp/ipykernel_96050/3858443391.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  guess.dtype = model.expparams_dtype


dtype([('t', '<f8')])

In [6]:
w_0, w_1 = updater.hypothetical_update(np.array([0, 1]), guess)

NameError: name 'guess' is not defined

In [7]:
w_0.shape

NameError: name 'w_0' is not defined

In [8]:
w_1.shape

NameError: name 'w_1' is not defined

In [9]:
w_0.dtype

NameError: name 'w_0' is not defined

In [10]:
w_0[0, :]

NameError: name 'w_0' is not defined

In [11]:
print(updater.particle_covariance_mtx(w_0[0, :], updater.particle_locations))

print(updater.particle_covariance_mtx(w_1[0, :], updater.particle_locations))


new_weights = [w_0, w_1]
np.linalg.norm(np.sum(np.array([updater.particle_covariance_mtx(w_i[0, :], updater.particle_locations) for w_i in new_weights ]), axis=1)/guess['t'])


NameError: name 'w_0' is not defined

In [12]:
guess.copy()

NameError: name 'guess' is not defined

In [13]:
updater.model.modelparam_names

['\\omega', 'J']

In [14]:
guess[updater.model.expparams_dtype]

NameError: name 'guess' is not defined

In [15]:
updater.particle_locations

array([[6.21925809e-01, 6.36380916e-02],
       [9.62741236e-01, 2.57567278e-01],
       [9.12188294e-01, 7.89844538e-01],
       [1.96281879e-01, 5.13610125e-01],
       [1.45065051e-02, 3.88006889e-02],
       [8.15999241e-01, 9.04155857e-01],
       [8.63198311e-01, 7.50513947e-01],
       [9.28588570e-02, 8.24524836e-01],
       [8.02407298e-01, 2.45220841e-01],
       [3.57553548e-01, 3.47706742e-02],
       [4.38465575e-01, 7.27534575e-01],
       [3.07812928e-02, 2.23691036e-01],
       [9.97145510e-01, 5.87109556e-01],
       [7.71836051e-01, 7.48075161e-01],
       [6.02903343e-01, 8.48845606e-01],
       [2.75881774e-01, 2.90269220e-01],
       [7.69033216e-01, 1.08813224e-01],
       [9.75441229e-01, 8.52210717e-02],
       [4.15480587e-01, 4.21225354e-01],
       [1.75962100e-01, 4.12411915e-01],
       [8.31975903e-01, 6.60894376e-01],
       [6.25454867e-02, 2.02404105e-01],
       [2.87366875e-01, 4.63653092e-01],
       [2.52509657e-01, 4.63869764e-01],
       [4.670121

In [16]:
def square(numbers):
    for n in numbers:
        yield n ** 2

In [17]:
gen = square([1, 2, 3])

In [18]:
list(gen)

[1, 4, 9]

In [19]:
list(square([1, 2, 3]))

[1, 4, 9]

In [20]:
prior.sample()

array([[0.20226809, 0.12070899]])

In [21]:
rng = np.random.default_rng(seed=1)
n_cases = 2
true_values_list = [np.array([0, rng.uniform(size=1)[0]]) for _ in range(n_cases)]

In [22]:
true_values_list

[array([0.        , 0.51182162]), array([0.       , 0.9504637])]

In [23]:
all_data = [[updater.est_covariance_mtx(), updater.est_covariance_mtx()], [updater.est_covariance_mtx(), updater.est_covariance_mtx()], [1, 2, 3]]
print(all_data)

[[array([[ 0.08353908, -0.00329702],
       [-0.00329702,  0.08048331]]), array([[ 0.08353908, -0.00329702],
       [-0.00329702,  0.08048331]])], [array([[ 0.08353908, -0.00329702],
       [-0.00329702,  0.08048331]]), array([[ 0.08353908, -0.00329702],
       [-0.00329702,  0.08048331]])], [1, 2, 3]]


In [24]:
[np.mean(i, axis=0) for i in all_data]

[array([[ 0.08353908, -0.00329702],
        [-0.00329702,  0.08048331]]),
 array([[ 0.08353908, -0.00329702],
        [-0.00329702,  0.08048331]]),
 2.0]

In [25]:
a = None
if not a:
    print("hola")

hola


In [26]:
np.mean([updater.est_covariance_mtx(), updater.est_covariance_mtx()], axis=0)

array([[ 0.08353908, -0.00329702],
       [-0.00329702,  0.08048331]])

In [27]:

from generate_experiments import run_case

rng = np.random.default_rng(seed=1)

number_of_cases = 3
number_of_shots = 3

true_values_list = [np.array([0, rng.uniform(size=1)[0]]) for _ in range(number_of_cases)]

[run_case(true_values_i, number_of_shots) for true_values_i in true_values_list]

/home/antonio/dev/simple-QLL/optimization.py:30: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  exp_param.dtype = model.expparams_dtype
/home/antonio/dev/simple-QLL/generate_experiments.py:47: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  exp_before.dtype = model.expparams_dtype
/home/antonio/dev/simple-QLL/generate_experiments.py:50: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  exp_after.dtype = model.expparams_dtype


Inf gain non-opt t [0.00755207].
Inf gain after opt [0.03287404].
Experimental time [(0.5679035,)]


IndexError: invalid index to scalar variable.

In [ ]:
import h5py

In [ ]:
hf = h5py.File("prueba.hdf5", "w")


In [ ]:
hf['/case_1/data'] = true_values_list


In [ ]:
hf['/case_1/data'].attrs['number_of_shots'] = 3

In [ ]:
with h5py.File("prueba.hdf5", "a") as data_file:
    # data_file['/case_1/data'] = true_values_list
    # data_file['/case_1/data'].attrs['number_of_shots'] = 3
    last_key = list(data_file.keys())[-1]
    


In [ ]:
case_no = int(last_key.lstrip("case_"))
new_case_no = case_no + 1
new_case = "case_" + str(new_case_no)
data_file[new_case]

In [ ]:
new_case

'case_2'

In [ ]:
# hf_in = h5py.File('prueba.hdf5', 'w')
hf_in.close()

In [ ]:
"case_1"

'case_1'

In [ ]:
last_case = list(hf_in.keys())[-1]

hf_in[str(last_case)]



TypeError: Not a location id (invalid object ID)

In [ ]:
list(hf_in.keys())

case_1 = hf_in['case_1/data']

In [ ]:
hf_in['case_1/data'][()]

array([[0.        , 0.51182162],
       [0.        , 0.9504637 ]])

In [28]:
aux_dict  = {"a" : [updater.est_covariance_mtx(), updater.est_covariance_mtx()],
     "b" : [updater.est_covariance_mtx(), updater.est_covariance_mtx()],
     "c" : [1, 2, 3]}

In [29]:
np.mean(aux_dict["a"], axis=0)

array([[ 0.08353908, -0.00329702],
       [-0.00329702,  0.08048331]])

In [30]:
aux_dict2 = aux_dict.copy()

In [31]:
aux_dict2["a"] = np.mean(aux_dict2["a"], axis=0)

# Prueba experimentos

In [3]:
import numpy as np
import qinfer as qi
import qutip as qu
import matplotlib.pyplot as plt
from custom_models import simple_precession_with_noise
from optimization import *

In [8]:
from generate_experiments import run_case

rng = np.random.default_rng(seed=1)

number_of_cases = 2
number_of_shots = 3

true_values_list = [np.array([[0, rng.uniform(0, 0.5, size=1)[0]]]) for _ in range(number_of_cases)]

# [run_case(true_values_i, number_of_shots) for true_values_i in true_values_list]

In [9]:
true_values_list

[array([[0.        , 0.25591081]]), array([[0.        , 0.47523185]])]

In [6]:
result_dictionary = [run_case(true_values_i, number_of_shots) for true_values_i in true_values_list]


/home/antonio/dev/simple-QLL/optimization.py:30: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  exp_param.dtype = model.expparams_dtype
/home/antonio/dev/simple-QLL/generate_experiments.py:49: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  exp_before.dtype = model.expparams_dtype
/home/antonio/dev/simple-QLL/generate_experiments.py:52: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  exp_after.dtype = model.expparams_dtype


Inf gain non-opt t [0.07567022].
Inf gain after opt [0.03081254].
Experimental time [(0.56722251,)]
True parameters: [[0.         0.51182162]]
Estimated parameters: [0.         0.35794498]
Difference squared: [[0.         0.02367802]]
Inf gain non-opt t [0.06561548].
Inf gain after opt [0.0308668].
Experimental time [(0.56779994,)]
True parameters: [[0.         0.51182162]]
Estimated parameters: [0.         0.34461201]
Difference squared: [[0.         0.02795906]]
Inf gain non-opt t [0.0761403].
Inf gain after opt [0.0307459].
Experimental time [(0.56830853,)]
True parameters: [[0.         0.51182162]]
Estimated parameters: [0.         0.33172599]
Difference squared: [[0.         0.03243444]]
Inf gain non-opt t [0.00404339].
Inf gain after opt [0.03002662].
Experimental time [(0.56706416,)]
True parameters: [[0.        0.9504637]]
Estimated parameters: [0.         0.35933256]
Difference squared: [[0.         0.34943602]]


/home/antonio/dev/simple-QLL/optimization.py:47: RuntimeWarning: divide by zero encountered in log
  ) + 0.1*(np.exp(scalar_exp_param) - np.log(scalar_exp_param))


Inf gain non-opt t [0.06821636].
Inf gain after opt [0.06821636].
Experimental time [(7.93915664,)]
True parameters: [[0.        0.9504637]]
Estimated parameters: [0.         0.43888888]
Difference squared: [[0.         0.26170879]]
Inf gain non-opt t [0.0293644].
Inf gain after opt [0.02016901].
Experimental time [(0.56581313,)]
True parameters: [[0.        0.9504637]]
Estimated parameters: [0.         0.42873054]
Difference squared: [[0.         0.27220549]]


In [10]:
from generate_experiments import compute_statistic

In [11]:
result_dictionary

[{'True values': array([[0.        , 0.51182162]]),
  'Number of particles': 150,
  'Number of shots': 3,
  'Estimated parameters': [array([0.        , 0.35794498]),
   array([0.        , 0.34461201]),
   array([0.        , 0.33172599])],
  'Estimate covariance': [array([[0.        , 0.        ],
          [0.        , 0.03742656]]),
   array([[0.        , 0.        ],
          [0.        , 0.03675729]]),
   array([[0.        , 0.        ],
          [0.        , 0.03591243]])],
  'Experimental times': [array([(0.56722251,)], dtype=[('t', '<f8')]),
   array([(0.56779994,)], dtype=[('t', '<f8')]),
   array([(0.56830853,)], dtype=[('t', '<f8')])]},
 {'True values': array([[0.       , 0.9504637]]),
  'Number of particles': 150,
  'Number of shots': 3,
  'Estimated parameters': [array([0.        , 0.35933256]),
   array([0.        , 0.43888888]),
   array([0.        , 0.42873054])],
  'Estimate covariance': [array([[0.       , 0.       ],
          [0.       , 0.0360574]]),
   array([[0. 

In [13]:
from unittest import result


compute_statistic(result_dictionary[0], "Estimated parameters")

{'True values': array([[0.        , 0.51182162]]),
 'Number of particles': 150,
 'Number of shots': 3,
 'Estimated parameters': [array([0.        , 0.35794498]),
  array([0.        , 0.34461201]),
  array([0.        , 0.33172599])],
 'Estimate covariance': [array([[0.        , 0.        ],
         [0.        , 0.03742656]]),
  array([[0.        , 0.        ],
         [0.        , 0.03675729]]),
  array([[0.        , 0.        ],
         [0.        , 0.03591243]])],
 'Experimental times': [array([(0.56722251,)], dtype=[('t', '<f8')]),
  array([(0.56779994,)], dtype=[('t', '<f8')]),
  array([(0.56830853,)], dtype=[('t', '<f8')])],
 'Estimated parameters_mean': array([0.      , 0.344761])}