In [1]:
import qutip as qu
import numpy as np

In [37]:
sx = qu.sigmaz()

sy = qu.sigmay()




In [38]:
sx.full()

array([[ 1.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j]])

In [39]:
qu.spre(sx).full() == np.kron(np.identity(np.prod(sx.full().shape[1])), sx.full())

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:
# zcsr_kron(fast_identity(np.prod(A.shape[1])), A.data)

In [33]:
np.kron(np.identity(np.prod(sx.full().shape[1])), sx.full())

array([[0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j]])

In [19]:
np.identity

<function numpy.identity(n, dtype=None, *, like=None)>

In [103]:
def my_spre(A: np.array) -> np.array:
    return np.kron(np.identity((A.shape[1])), A)

def my_spost(A: np.array) -> np.array:
    return np.kron(A.T, np.identity((A.shape[1])))    

In [105]:
A = qu.sigmax()
qu.spost(A).full() == my_spost(A.full())

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [64]:
def dag(A: np.array) -> np.array:
    return np.conjugate(np.transpose(A))
    

In [63]:
def dissipator(A: np.array) -> np.array:
    return my_spre(A) @ my_spost(dag(A)) - 0.5 * my_spre(dag(A)@A) - 0.5 * my_spost(dag(A)@A)

In [61]:
dissipator(qu.sigmax().full())

array([[-1.+0.j,  0.+0.j,  0.+0.j,  1.+0.j],
       [ 0.+0.j, -1.+0.j,  1.+0.j,  0.+0.j],
       [ 0.+0.j,  1.+0.j, -1.+0.j,  0.+0.j],
       [ 1.+0.j,  0.+0.j,  0.+0.j, -1.+0.j]])

In [62]:
qu.lindblad_dissipator(qu.sigmax()).full()

array([[-1.+0.j,  0.+0.j,  0.+0.j,  1.+0.j],
       [ 0.+0.j, -1.+0.j,  1.+0.j,  0.+0.j],
       [ 0.+0.j,  1.+0.j, -1.+0.j,  0.+0.j],
       [ 1.+0.j,  0.+0.j,  0.+0.j, -1.+0.j]])

In [59]:
qu.sigmax().full() @ qu.sigmax().full()

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

In [102]:
def lindblad_hamiltonian_part(A: np.array) -> np.array:
    return -1j * (my_spre(A) - my_spost(A))

def my_liouvillian(H:np.array,  jump_op: np.array) -> np.array:
    return lindblad_hamiltonian_part(H)    +  dissipator(jump_op) 

In [98]:
H = 0.7*qu.sigmaz()
jump_op = qu.sigmax()
gamma = 0.2

In [101]:
qu.liouvillian(H, gamma*jump_op).full() == my_liouvillian(H.full(), gamma*jump_op.full())

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

array([[-0.04+0.j ,  0.  +0.j ,  0.  +0.j ,  0.04+0.j ],
       [ 0.  +0.j , -0.04+1.4j,  0.04+0.j ,  0.  +0.j ],
       [ 0.  +0.j ,  0.04+0.j , -0.04-1.4j,  0.  +0.j ],
       [ 0.04+0.j ,  0.  +0.j ,  0.  +0.j , -0.04+0.j ]])